import { useState } from 'react';

const s = {
  wrapper: { overflow: 'auto', height: '100%', padding: '16px' },
  table: { width: '100%', borderCollapse: 'collapse', fontSize: '12px' },
  th: {
    background: '#1a1d27', color: '#9ca3af', padding: '8px 12px',
    textAlign: 'left', fontWeight: 600, borderBottom: '1px solid #2d3148',
    cursor: 'pointer', userSelect: 'none', whiteSpace: 'nowrap',
  },
  tdBase: { padding: '7px 12px', borderBottom: '1px solid #1e2235', whiteSpace: 'nowrap' },
  win: { color: '#34d399' },
  loss: { color: '#f87171' },
  breakeven: { color: '#fbbf24' },
  buy: { background: 'rgba(52, 211, 153, 0.08)' },
  sell: { background: 'rgba(248, 113, 113, 0.08)' },
};

export default function TradeLog({ trades }) {
  const [sortKey, setSortKey] = useState('id');
  const [sortDir, setSortDir] = useState(1);

  function handleSort(key) {
    if (sortKey === key) setSortDir(d => -d);
    else { setSortKey(key); setSortDir(1); }
  }

  const sorted = [...trades].sort((a, b) => {
    let va = a[sortKey], vb = b[sortKey];
    if (typeof va === 'string') return sortDir * va.localeCompare(vb);
    return sortDir * (va - vb);
  });

  const HCol = ({ label, k }) => (
    <th style={s.th} onClick={() => handleSort(k)}>
      {label} {sortKey === k ? (sortDir === 1 ? '▲' : '▼') : ''}
    </th>
  );

  return (
    <div style={s.wrapper}>
      <table style={s.table}>
        <thead>
          <tr>
            <HCol label="#" k="id" />
            <HCol label="Side" k="side" />
            <HCol label="Entry Time" k="entryTime" />
            <HCol label="Entry ₹" k="entryPrice" />
            <HCol label="Exit Time" k="exitTime" />
            <HCol label="Exit ₹" k="exitPrice" />
            <HCol label="Qty" k="qty" />
            <HCol label="Gross P&L" k="grossPnl" />
            <HCol label="Brokerage" k="brokerage" />
            <HCol label="Net P&L" k="netPnl" />
            <HCol label="Exit Reason" k="exitReason" />
            <HCol label="Outcome" k="outcome" />
          </tr>
        </thead>
        <tbody>
          {sorted.map(t => {
            const outcomeStyle = t.outcome === 'WIN' ? s.win : t.outcome === 'LOSS' ? s.loss : s.breakeven;
            const rowBg = t.side === 'BUY' ? s.buy : s.sell;
            return (
              <tr key={t.id} style={rowBg}>
                <td style={s.tdBase}>{t.id}</td>
                <td style={{ ...s.tdBase, fontWeight: 600, ...(t.side === 'BUY' ? s.win : s.loss) }}>{t.side}</td>
                <td style={s.tdBase}>{t.entryTimeIST}</td>
                <td style={s.tdBase}>₹{t.entryPrice}</td>
                <td style={s.tdBase}>{t.exitTimeIST}</td>
                <td style={s.tdBase}>₹{t.exitPrice}</td>
                <td style={s.tdBase}>{t.qty}</td>
                <td style={{ ...s.tdBase, ...(t.grossPnl >= 0 ? s.win : s.loss) }}>₹{t.grossPnl}</td>
                <td style={s.tdBase}>₹{t.brokerage}</td>
                <td style={{ ...s.tdBase, fontWeight: 700, ...outcomeStyle }}>
                  {t.netPnl >= 0 ? '+' : ''}₹{t.netPnl}
                </td>
                <td style={{ ...s.tdBase, color: '#9ca3af', fontSize: '11px' }}>{t.exitReason}</td>
                <td style={{ ...s.tdBase, fontWeight: 600, ...outcomeStyle }}>{t.outcome}</td>
              </tr>
            );
          })}
        </tbody>
      </table>
      {trades.length === 0 && (
        <div style={{ textAlign: 'center', padding: '40px', color: '#4b5563' }}>
          No trades generated by this strategy in the selected period.
        </div>
      )}
    </div>
  );
}
